version: "2"
services:
    mongo:
        image: mongo
        volumes:
            - /data/mongodb/db:/data/db
        ports:
            - "27017:27017"
    backend-exercise:
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo